//CORE_REFERENCE_IMPORTS
//CORE_REFERENCE_IMPORT-Claim-SSD_SERVICE_ID_sd_vFzTkEYpoBQQlG0l
import { Claim as SSD_SERVICE_ID_sd_vFzTkEYpoBQQlG0l } from './sd-services/Claim';
//CORE_REFERENCE_IMPORT-Policy-SSD_SERVICE_ID_sd_Fsla18Y64Y7RqBdK
import { Policy as SSD_SERVICE_ID_sd_Fsla18Y64Y7RqBdK } from './sd-services/Policy';

export const UserRoutes = [
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-Claim-SSD_SERVICE_ID_sd_vFzTkEYpoBQQlG0l
SSD_SERVICE_ID_sd_vFzTkEYpoBQQlG0l,
//CORE_REFERENCE_PUSH_TO_ROUTE_ARRAY-Policy-SSD_SERVICE_ID_sd_Fsla18Y64Y7RqBdK
SSD_SERVICE_ID_sd_Fsla18Y64Y7RqBdK,
];
